apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-ui-v1
  namespace: default
  labels:
    k8s-app: kube-ui
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kube-ui
    version: v1
  template:
    metadata:
      labels:
        k8s-app: kube-ui
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: kube-ui
        image: gcr.io/kube-ui/kube-ui:dev
        ports:
        - containerPort: 8080
